AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Esta plantilla sirve para crear la infraestructura para el despliegue de una pagina dinamica con formulario.
  Primero se establecerán los grupos de seguridad para la instancia frontend y la instancia backend.
  Despues estableceremos una direccion IP elastica para la instancia frontend y procederemos a crear las dos instancias.


Parameters:
  IdAmi:
    Type: String
    Default: ami-06878d265978313ca

  Ram4Gb:
    Type: String
    Default: t2.medium

  Ram8Gb:
    Type: String
    Default: t2.large

  FrontendInstanceName:
    Type: String
    Default: iaw-practica-07-frontend

  BackendInstanceName:
    Type: String
    Default: iaw-practica-07-backend

  KeyFileName:
    Type: String
    Default: vockey

  FrontendSecurityGroupName:
    Type: String
    Default: SG_Frontend_No_Balancer_07

  FrontendSecurityGroupDescription:
    Type: String
    Default: Grupo de seguridad para la instancia frontend sin balanceador de carga

  BackendSecurityGroupName:
    Type: String
    Default: SG_Backend_07

  BackendSecurityGroupDescription:
    Type: String
    Default: Grupo de seguridad para las instancias backend

  SgIpProtocol:
    Type: String
    Default: tcp
  
  SgCidrIp:
    Type: String
    Default: 0.0.0.0/0

  SshPort:
    Type: String
    Default: 22

  HttpsPort:
    Type: String
    Default: 443

  HttpPort:
    Type: String
    Default: 80

  SqlPort:
    Type: String
    Default: 3306


Resources:
  FrontendNoBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:
        Ref: FrontendSecurityGroupName
      GroupDescription:
        Ref: FrontendSecurityGroupDescription
      SecurityGroupIngress:
        - IpProtocol:
            Ref: SgIpProtocol
          FromPort:
            Ref: SshPort
          ToPort:
            Ref: SshPort
          CidrIp:
            Ref: SgCidrIp

        - IpProtocol:
            Ref: SgIpProtocol
          FromPort:
            Ref: HttpsPort
          ToPort:
            Ref: HttpsPort
          CidrIp:
            Ref: SgCidrIp

        - IpProtocol:
            Ref: SgIpProtocol
          FromPort:
            Ref: HttpPort
          ToPort:
            Ref: HttpPort
          CidrIp:
            Ref: SgCidrIp


  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:
        Ref: BackendSecurityGroupName
      GroupDescription:
        Ref: BackendSecurityGroupDescription
      SecurityGroupIngress:
        - IpProtocol:
            Ref: SgIpProtocol
          FromPort:
            Ref: SshPort
          ToPort:
            Ref: SshPort
          CidrIp:
            Ref: SgCidrIp

        - IpProtocol:
            Ref: SgIpProtocol
          FromPort:
            Ref: SqlPort
          ToPort:
            Ref: SqlPort
          CidrIp:
            Ref: SgCidrIp


  FrontendInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: IdAmi
      InstanceType:
        Ref: Ram4Gb
      SecurityGroups:
        - !Ref FrontendNoBalancerSecurityGroup
      KeyName:
        Ref: KeyFileName
      Tags:
        - Key: Name
          Value:
            Ref: FrontendInstanceName


  BackendInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: IdAmi
      InstanceType:
        Ref: Ram8Gb
      SecurityGroups:
        - !Ref BackendSecurityGroup
      KeyName:
        Ref: KeyFileName
      Tags:
        - Key: Name
          Value:
            Ref: BackendInstanceName


  FrontendElascticIp:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref FrontendInstance